Booking days off
danutDiac/tsa-node-project pull request #16
Opened 2018-05-30 11:03 UTC by Taniaf26

2018-05-31 17:42 UTC, h-mihail commented on doc/BookingDaysOff.md
> +Returns a JSON with days off from an user
Creates a new entry*

2018-05-31 17:45 UTC, h-mihail commented on logs/errors.log
> +[2018-05-31T10:27:02+03:00] GET "/users/%220%22" 404 Not Found - {}
This should be added to ```.gitignore```

2018-05-31 19:08 UTC, Taniaf26 commented on src/actions/bookingDaysOffActions.js
> +        let day = "";
nu mai sunt folosite month si day

2018-05-31 19:17 UTC, h-mihail commented on src/actions/bookingDaysOffActions.js
> +const fs = require("fs");
fs module can be removed now

2018-06-04 08:43 UTC, andreicioromila requested changes

2018-06-04 08:43 UTC, andreicioromila commented on src/actions/bookingDaysOffActions.js
> +    return date !== undefined && typeof date === "string" && regex.test(date) ;
Do you need all these conditions?

2018-06-04 13:50 UTC, h-mihail submitted a review, later dismissed

2018-06-04 13:51 UTC, h-mihail reviewed
.

2018-06-07 07:58 UTC, climandrei94 submitted a review, later dismissed

2018-06-07 10:18 UTC, andreicioromila submitted a review, later dismissed

2018-06-07 10:22 UTC, climandrei94 submitted a review, later dismissed

2018-06-07 10:28 UTC, ghost approved these changes

2018-06-07 10:30 UTC, climandrei94 approved these changes

2018-06-07 10:39 UTC, h-mihail approved these changes

2018-06-07 10:40 UTC, merged