Get users refactor
danutDiac/tsa-node-project pull request #26
Opened 2018-06-05 11:32 UTC by MihaiBojescu

Refactored get users.

2018-06-06 08:32 UTC, iosifboanca commented
I suggest to have a short briefing at our meeting before reviewing and accepting the last commit.

2018-06-06 08:35 UTC, danutDiac commented on src/helpers/helpers.js
> +        .then(p => {
Remove this, as it does nothing (no added value)

2018-06-06 08:39 UTC, danutDiac commented on tests/getUsersActions.test.js
> +                const output = findItemById(users, userId);
**findItemById** e o metoda abstracta care poate fi folosita in mai multe locuri si de aceea numele ei e ok asa
In momentul in care o folosesti, tu stii ce rezultat iti va returna.
Denumeste sugestiv variabila in care salvezi rezultatul.
Ex:
const **foundUser** = findItemById(users, userId);
let **testUser** = users[0];
chai.expect(**foundUser**).to.deep.equal(**testUser**);

2018-06-06 09:40 UTC, andreicioromila requested changes

2018-06-06 09:40 UTC, andreicioromila commented on src/actions/getUsersActions.js
> +    return new Promise((resolve, reject) => {
Since `readFile` already returns a promise, can you do without creating a new promise here?

2018-06-06 09:40 UTC, andreicioromila commented on src/helpers/helpers.js
> +const parseJSON = data => {
Can someone provide an explanation for why is this promisified wrapper over the `JSON.parse` function necessary?

2018-06-07 07:59 UTC, climandrei94 submitted a review, later dismissed

2018-06-07 10:16 UTC, andreicioromila approved these changes

2018-06-07 10:21 UTC, ghost approved these changes

2018-06-07 10:22 UTC, climandrei94 approved these changes

2018-06-07 10:23 UTC, merged