DELETE /users/:id
danutDiac/tsa-node-project pull request #9
Opened 2018-05-25 11:33 UTC by h-mihail

Finished endpoint for delete users.

2018-05-25 12:50 UTC, MihaiBojescu commented on db/users.json
> +[{"id":0,"firstName":"","lastName":"","email":"","phone":""}]
Formatting the JSON would help it's readability (as it is just for reference).

2018-05-25 13:44 UTC, andreicioromila requested changes

2018-05-25 13:44 UTC, andreicioromila commented on doc/deleteUser.md
> +# Retriving user details
typo

2018-05-25 13:44 UTC, andreicioromila commented on src/routes/users.js
> +    for (let i = 0; i < users.length; i++) {
check `Array.find()`

2018-05-25 13:44 UTC, andreicioromila commented on src/routes/users.js
> +function deleteUsers(req, res) {
In order to avoid conflicts, your other colleagues moved the implementation to a different file in the actions folder. See if you can sync between teams

2018-05-25 13:44 UTC, andreicioromila commented on tests/users.test.js
> +describe('DELETE /users/:id', function () {
these integration tests are really nice!
Please also add unit tests for exactly the logic you have for deleting users (which don't take into consideration the http server)

2018-05-25 13:44 UTC, andreicioromila commented on src/main.js
> +module.exports = app
Why is `app` exported?

2018-05-25 14:36 UTC, h-mihail commented on src/main.js
> +module.exports = app
I export app so i can use chai.request(app).get(...).end(...)

2018-05-29 09:35 UTC, andreicioromila submitted a review, later dismissed

2018-05-29 09:36 UTC, MihaiBojescu submitted a review, later dismissed

2018-05-29 09:36 UTC, MihaiBojescu commented on doc/deleteUser.md
> +    fetch("localhost:3000/users/0");
The method should be
```javascript
fetch("localhost:3000/users/0", { method: "DELETE" });
```
as seen on [link](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch). (Otherwise fetch would use `GET`)

2018-05-29 09:44 UTC, andradnl submitted a review, later dismissed

2018-05-29 10:01 UTC, DemetriadS submitted a review, later dismissed

2018-05-29 13:28 UTC, andreicioromila approved these changes

2018-05-29 13:28 UTC, andreicioromila commented on src/actions/deleteUserActions.js
> +let findUser = (users, id) => {
Did you get the chance to sync with the other teams regarding `findUser` implementation?

2018-05-29 15:57 UTC, MihaiBojescu approved these changes

2018-05-29 19:45 UTC, iosifboanca approved these changes

2018-05-30 07:09 UTC, merged